import { getSupabaseAdmin } from "./supabaseAdmin.js";
import { PRICE_TABLE, type PriceEntry } from "./prices.js";

/**
 * Server-truth prices, read from the database.
 *
 * WHAT CHANGED AND WHY
 * Prices used to live in api/_lib/prices.ts, a table hand-copied from
 * src/data/products.ts. Two copies of every price meant they could silently disagree,
 * and the file itself warned that it had to be regenerated by hand after any edit.
 * Now that the admin dashboard writes prices to the `products` table, that table is
 * the only place a price is authored, so this reads from it directly.
 *
 * PRICE_TABLE survives purely as a fallback for the window before the catalogue is
 * seeded (and if the database is briefly unreachable). It is no longer authoritative
 * and no longer needs maintaining — once the seed has run, every lookup comes from
 * the database.
 *
 * This is still the *server's* price: it is what gets hashed for PayU and charged.
 * A client-sent amount is never trusted, exactly as before.
 */

type Cached = { at: number; prices: Record<string, PriceEntry> };

/** Serverless instances are reused between invocations, so a short in-memory cache
 *  saves a query per checkout without letting a price edit go unnoticed for long. */
let cache: Cached | null = null;
const TTL_MS = 30_000;

async function loadPrices(): Promise<Record<string, PriceEntry>> {
  if (cache && Date.now() - cache.at < TTL_MS) return cache.prices;

  const admin = getSupabaseAdmin();
  if (!admin) return PRICE_TABLE;

  try {
    // Archived products are included deliberately: an order placed seconds before a
    // product was archived must still price correctly at the callback.
    const { data, error } = await admin
      .from("products")
      .select("id, price, compare_at, price_by_volume");

    if (error || !data?.length) {
      if (error) console.error("priceSource: falling back to static table —", error.message);
      return PRICE_TABLE;
    }

    const prices: Record<string, PriceEntry> = {};
    for (const row of data) {
      prices[row.id] = {
        price: Number(row.price),
        compareAt: row.compare_at != null ? Number(row.compare_at) : null,
        priceByVolume: (row.price_by_volume as PriceEntry["priceByVolume"]) ?? null,
      };
    }

    cache = { at: Date.now(), prices };
    return prices;
  } catch (err) {
    console.error("priceSource: unexpected error, using static table", err);
    return PRICE_TABLE;
  }
}

/**
 * Unit price for a product/size, or null when the product is unknown.
 *
 * Returning null (rather than 0 or a guess) is what lets the caller reject the whole
 * order: an unknown id must fail the checkout, never quietly price at zero.
 */
export async function priceForServerAsync(
  productId: string,
  volume?: string
): Promise<number | null> {
  const prices = await loadPrices();
  const entry = prices[productId];
  if (!entry) return null;
  if (volume && entry.priceByVolume && entry.priceByVolume[volume]) {
    return entry.priceByVolume[volume].price;
  }
  return entry.price;
}

/** Test hook — forces the next lookup to re-read the database. */
export function clearPriceCache(): void {
  cache = null;
}

export { FREE_SHIPPING_THRESHOLD, SHIPPING_FEE, GIFT_WRAP_FEE } from "./prices.js";
